// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwRkEBCVX94JpRVt0ueFFlnj_DXVkmbSU',
    appId: '1:801735047423:web:229f8d95965b36984af4ca',
    messagingSenderId: '801735047423',
    projectId: 'tomo-5e10d',
    authDomain: 'tomo-5e10d.firebaseapp.com',
    storageBucket: 'tomo-5e10d.firebasestorage.app',
    measurementId: 'G-8MX87L1P5N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjwsgRRmwYT4CsZfTud44UA5eHHEi4T40',
    appId: '1:801735047423:android:1a439b40fcff95714af4ca',
    messagingSenderId: '801735047423',
    projectId: 'tomo-5e10d',
    storageBucket: 'tomo-5e10d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRD-SXhnE4EyeKifObeYwfXi9WuQPyB0Y',
    appId: '1:801735047423:ios:0dcfc481512cdbd84af4ca',
    messagingSenderId: '801735047423',
    projectId: 'tomo-5e10d',
    storageBucket: 'tomo-5e10d.firebasestorage.app',
    iosBundleId: 'com.example.mobileSocialNetwork',
  );
}
